# Copyright Red Hat
# Run `make samples` if you modified the orginal file located in the project resources directory
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: compute-apis
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: serviceaccounts
  - group: workload.kcp.dev
    resource: synctargets
    identityHash: 30f34972de5a87d83a8f337f61599649f2752680d50bb28c9282d15109afc031
  - group: "rbac.authorization.k8s.io"
    resource: clusterroles
  - group: "rbac.authorization.k8s.io"
    resource: clusterrolebindings
  latestResourceSchemas:
  - latest.registeredclusters.singapore.open-cluster-management.io

---
