# Copyright Red Hat
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute-operator-manager-role
rules:
# Setting this first rule as a convenience for installing the APIResourceSchema and APIExports
# using service account kubeconfig file on hand via Makefile
- apiGroups: ["apis.kcp.dev"]
  resources: ["apiresourceschemas", "apiexports"]
  verbs: ["create", "update", "patch", "get"]
- apiGroups: ["apis.kcp.dev"]
  resources: ["apiexports"]
  verbs: ["get", "list"]
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/content
  resourceNames:
  - compute-apis
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
