# Copyright Red Hat
# Run `make samples` if you modified the orginal file located in the project resources directory
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: compute-operator
spec:
  reference:
    workspace:
      path: root:{{ .Organization }}
      exportName: compute-apis
